on:
  workflow_dispatch:

jobs:
  build:
    name: Build Web Assembly Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build web assembly
        run: pygbag .
