on:
  workflow_dispatch:
name: Build and Deploy
jobs:
  build:
    name: Build Web Assembly Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: pip install -r ./requirements.txt

      - name: Build web assembly
        run: pygbag --build .

      - name: Adjust screen X size reference
        run: sed -i 's/REFX = 1980/REFX = 640/' ./build/web/index.html

      - name: Adjust screen Y size reference
        run: sed -i 's/REFY = 1080/REFY = 480/' ./build/web/index.html  

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SKY_046A4970F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./build/web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######