on:
  workflow_dispatch:
name: Build and Deploy
jobs:
  build:
    name: Build Web Assembly Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: List directory structure
        run: ls -l

      - name: Install Dependencies
        run: pip install -r ./requirements.txt

      - name: Build web assembly
        run: pygbag .
