on:
  workflow_dispatch:

jobs:
  build:
    name: Build Web Assembly Artifact
    runs-on: ubuntu-latest
    steps:
      - name: List directory structure
        run: ls -l

      - name: Install Dependencies
        run: pip install -r ./valos-run/requirements.txt

      - name: Build web assembly
        run: pygbag valos-run
