on:
  workflow_dispatch:

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build web assembly
        run: pygbag .
